### ISSUE TITLE
License

### ISSUE THREAD

**Issue by m4tx** [jkbonfield/rans_static#1] opened 2022-03-14 19:43 UTC
Could you please add a license for the project? Right now there is none, which basically disallows anybody from using your code for any purpose.

**Comment by jkbonfield** [comment] 2022-03-15 09:01
This was just a highly experimental set of rans implementations, but it was intended to be public (likely BSD, but as you say I never chose an explicit license).

However, please see https://github.com/samtools/htscodecs/ as a more up to date implementation, with SIMD support and more features.   Specifically the 4x16 variant has an option to turn it into 32x16 unrolling, which comes at a cost of increasing the minimum compressed size, but with AVX2 instructions can achieve speeds in excess of 1GB/s.

**Comment by m4tx** [comment] 2022-03-16 15:15
Makes sense, thank you so much!

**Comment by jkbonfield** [comment] 2022-03-16 15:35
I updated the README file to point to the newer repository.  I'll close this (without bothering to think too hard on license as this was basically just experimental work before tidying up for production usage).

**Closed as completed by jkbonfield** 2022-03-16 15:35 UTC
